export const ADD_DECK = 'ADD_DECK'
export const LOAD_DECKS = 'LOAD_DECKS'
export const ADD_CARD = 'ADD_CARD'
export const LOAD_CARDS = 'LOAD_CARDS'
export const ADD_QUIZ_ANSWER = 'ADD_QUIZ_ANSWER'
export const CLEAR_QUIZ = 'CLEAR_QUIZ'